# Generated by Django 3.1.6 on 2021-11-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_field',
        ),
    ]
