# Generated by Django 3.1.6 on 2021-12-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_auto_20211130_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
