# Generated by Django 3.1.6 on 2021-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_remove_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visited_date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
