# Generated by Django 3.1.6 on 2021-12-02 02:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0006_auto_20211201_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(default='No description provided'),
            preserve_default=False,
        ),
    ]
